version: '3.1'

services:

  db:
    image: postgres:12-alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=restapi_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
